// Generated by tools/publish_champion_edition_assets.py. Do not edit manually.

export const CHAMPION_ARTWORK_BY_EDITION: Record<string, { src: string }> = {
  // campeonato_brasileiro_serie_a_2021/018.jpg
  "brasileirao_a::2021": { src: "/images/competition-season/editions/brasileirao_a__2021.jpg" },
  // campeonato_brasileiro_serie_a_2022/021.jpg
  "brasileirao_a::2022": { src: "/images/competition-season/editions/brasileirao_a__2022.jpg" },
  // campeonato_brasileiro_serie_a_2023/023.jpg
  "brasileirao_a::2023": { src: "/images/competition-season/editions/brasileirao_a__2023.jpg" },
  // campeonato_brasileiro_serie_a_2024/012.png
  "brasileirao_a::2024": { src: "/images/competition-season/editions/brasileirao_a__2024.png" },
  // campeonato_brasileiro_serie_a_2025/017.jpg
  "brasileirao_a::2025": { src: "/images/competition-season/editions/brasileirao_a__2025.jpg" },
  // campeonato_brasileiro_serie_b_2021/011.png
  "brasileirao_b::2021": { src: "/images/competition-season/editions/brasileirao_b__2021.png" },
  // campeonato_brasileiro_serie_b_2022/005.jpg
  "brasileirao_b::2022": { src: "/images/competition-season/editions/brasileirao_b__2022.jpg" },
  // campeonato_brasileiro_serie_b_2023/007.jpg
  "brasileirao_b::2023": { src: "/images/competition-season/editions/brasileirao_b__2023.jpg" },
  // campeonato_brasileiro_serie_b_2024/011.jpg
  "brasileirao_b::2024": { src: "/images/competition-season/editions/brasileirao_b__2024.jpg" },
  // campeonato_brasileiro_serie_b_2025/014.jpeg
  "brasileirao_b::2025": { src: "/images/competition-season/editions/brasileirao_b__2025.jpeg" },
  // bundesliga_2021_2022/024.jpg
  "bundesliga::2021/2022": { src: "/images/competition-season/editions/bundesliga__2021_2022.jpg" },
  // bundesliga_2022_2023/018.jpg
  "bundesliga::2022/2023": { src: "/images/competition-season/editions/bundesliga__2022_2023.jpg" },
  // bundesliga_2023_2024/012.jpg
  "bundesliga::2023/2024": { src: "/images/competition-season/editions/bundesliga__2023_2024.jpg" },
  // bundesliga_2024_2025/008.jpg
  "bundesliga::2024/2025": { src: "/images/competition-season/editions/bundesliga__2024_2025.jpg" },
  // uefa_champions_league_2021_2022/003.jpg
  "champions_league::2021/2022": { src: "/images/competition-season/editions/champions_league__2021_2022.jpg" },
  // uefa_champions_league_2022_2023/004.jpeg
  "champions_league::2022/2023": { src: "/images/competition-season/editions/champions_league__2022_2023.jpeg" },
  // uefa_champions_league_2023_2024/001.jpeg
  "champions_league::2023/2024": { src: "/images/competition-season/editions/champions_league__2023_2024.jpeg" },
  // uefa_champions_league_2024_2025/022.jpg
  "champions_league::2024/2025": { src: "/images/competition-season/editions/champions_league__2024_2025.jpg" },
  // copa_do_brasil_2021/001.jpg
  "copa_do_brasil::2021": { src: "/images/competition-season/editions/copa_do_brasil__2021.jpg" },
  // copa_do_brasil_2022/025.jpg
  "copa_do_brasil::2022": { src: "/images/competition-season/editions/copa_do_brasil__2022.jpg" },
  // copa_do_brasil_2023/007.jpg
  "copa_do_brasil::2023": { src: "/images/competition-season/editions/copa_do_brasil__2023.jpg" },
  // copa_do_brasil_2024/019.jpeg
  "copa_do_brasil::2024": { src: "/images/competition-season/editions/copa_do_brasil__2024.jpeg" },
  // copa_do_brasil_2025/018.jpg
  "copa_do_brasil::2025": { src: "/images/competition-season/editions/copa_do_brasil__2025.jpg" },
  // fifa_intercontinental_cup_2024/001.jpg
  "fifa_intercontinental_cup::2024": { src: "/images/competition-season/editions/fifa_intercontinental_cup__2024.jpg" },
  // la_liga_2021_2022/009.jpg
  "la_liga::2021/2022": { src: "/images/competition-season/editions/la_liga__2021_2022.jpg" },
  // la_liga_2022_2023/019.jpeg
  "la_liga::2022/2023": { src: "/images/competition-season/editions/la_liga__2022_2023.jpeg" },
  // la_liga_2023_2024/023.jpeg
  "la_liga::2023/2024": { src: "/images/competition-season/editions/la_liga__2023_2024.jpeg" },
  // la_liga_2024_2025/020.jpg
  "la_liga::2024/2025": { src: "/images/competition-season/editions/la_liga__2024_2025.jpg" },
  // copa_libertadores_da_america_2021/002.jpg
  "libertadores::2021": { src: "/images/competition-season/editions/libertadores__2021.jpg" },
  // copa_libertadores_da_america_2022/022.jpg
  "libertadores::2022": { src: "/images/competition-season/editions/libertadores__2022.jpg" },
  // copa_libertadores_da_america_2023/007.jpg
  "libertadores::2023": { src: "/images/competition-season/editions/libertadores__2023.jpg" },
  // copa_libertadores_da_america_2024/020.jpg
  "libertadores::2024": { src: "/images/competition-season/editions/libertadores__2024.jpg" },
  // copa_libertadores_da_america_2025/014.jpg
  "libertadores::2025": { src: "/images/competition-season/editions/libertadores__2025.jpg" },
  // ligue_1_2021_2022/005.jpg
  "ligue_1::2021/2022": { src: "/images/competition-season/editions/ligue_1__2021_2022.jpg" },
  // ligue_1_2022_2023/012.jpg
  "ligue_1::2022/2023": { src: "/images/competition-season/editions/ligue_1__2022_2023.jpg" },
  // ligue_1_2023_2024/018.jpg
  "ligue_1::2023/2024": { src: "/images/competition-season/editions/ligue_1__2023_2024.jpg" },
  // ligue_1_2024_2025/014.jpg
  "ligue_1::2024/2025": { src: "/images/competition-season/editions/ligue_1__2024_2025.jpg" },
  // premier_league_2021_2022/018.jpg
  "premier_league::2021/2022": { src: "/images/competition-season/editions/premier_league__2021_2022.jpg" },
  // premier_league_2022_2023/023.jpg
  "premier_league::2022/2023": { src: "/images/competition-season/editions/premier_league__2022_2023.jpg" },
  // premier_league_2023_2024/021.jpeg
  "premier_league::2023/2024": { src: "/images/competition-season/editions/premier_league__2023_2024.jpeg" },
  // premier_league_2024_2025/019.jpg
  "premier_league::2024/2025": { src: "/images/competition-season/editions/premier_league__2024_2025.jpg" },
  // liga_portugal_2023_2024/016.jpeg
  "primeira_liga::2023/2024": { src: "/images/competition-season/editions/primeira_liga__2023_2024.jpeg" },
  // liga_portugal_2024_2025/016.jpg
  "primeira_liga::2024/2025": { src: "/images/competition-season/editions/primeira_liga__2024_2025.jpg" },
  // serie_a_italia_2021_2022/018.jpg
  "serie_a_italy::2021/2022": { src: "/images/competition-season/editions/serie_a_italy__2021_2022.jpg" },
  // serie_a_italia_2022_2023/001.jfif
  "serie_a_italy::2022/2023": { src: "/images/competition-season/editions/serie_a_italy__2022_2023.jpg" },
  // serie_a_italia_2023_2024/020.jpg
  "serie_a_italy::2023/2024": { src: "/images/competition-season/editions/serie_a_italy__2023_2024.jpg" },
  // serie_a_italia_2024_2025/004.jpg
  "serie_a_italy::2024/2025": { src: "/images/competition-season/editions/serie_a_italy__2024_2025.jpg" },
  // copa_sudamericana_2024/003.jpg
  "sudamericana::2024": { src: "/images/competition-season/editions/sudamericana__2024.jpg" },
  // copa_sudamericana_2025/001.jpeg
  "sudamericana::2025": { src: "/images/competition-season/editions/sudamericana__2025.jpeg" },
  // supercopa_do_brasil_2025/012.jpg
  "supercopa_do_brasil::2025": { src: "/images/competition-season/editions/supercopa_do_brasil__2025.jpg" },
};
