version: 2

models:
  - name: team_monthly_stats
    description: "Agregado mensal por time."
    tests:
      - unique_combination_of_columns:
          combination_of_columns:
            - season
            - year
            - month
            - team_sk
    columns:
      - name: season
        description: "Temporada do agregado."
        tests:
          - not_null
      - name: year
        description: "Ano do periodo agregado."
        tests:
          - not_null
      - name: month
        description: "Mes do periodo agregado em formato MM."
        tests:
          - not_null
          - accepted_values:
              values: ['01', '02', '03', '04', '05', '06', '07', '08', '09', '10', '11', '12']
      - name: team_sk
        description: "Chave substituta do time."
        tests:
          - not_null
          - relationships:
              to: ref('dim_team')
              field: team_sk
      - name: team_id
        description: "Identificador natural do time."
        tests:
          - not_null
      - name: team_name
        description: "Nome do time."
        tests:
          - not_null
      - name: matches
        description: "Quantidade de partidas do time no mes."
        tests:
          - not_null

  - name: standings_evolution
    description: "Evolucao rodada a rodada por time no grain competicao/temporada/time/rodada."
    tests:
      - unique_combination_of_columns:
          combination_of_columns:
            - competition_sk
            - season
            - team_id
            - round_key
    columns:
      - name: competition_sk
        description: "Chave substituta da competicao."
        tests:
          - not_null
          - relationships:
              to: ref('dim_competition')
              field: competition_sk
      - name: league_id
        description: "Identificador natural da liga."
        tests:
          - not_null
      - name: season
        description: "Temporada."
        tests:
          - not_null
      - name: round_key
        description: "Chave numerica e estavel da rodada usada no acumulado."
        tests:
          - not_null
      - name: round
        description: "Alias legado da chave de rodada."
        tests:
          - not_null
      - name: team_sk
        description: "Chave substituta do time."
        tests:
          - not_null
          - relationships:
              to: ref('dim_team')
              field: team_sk
      - name: team_id
        description: "Identificador natural do time."
        tests:
          - not_null
      - name: points_accumulated
        description: "Pontos acumulados ate a rodada."
        tests:
          - not_null
      - name: goals_for_accumulated
        description: "Gols marcados acumulados ate a rodada."
        tests:
          - not_null
      - name: goal_diff_accumulated
        description: "Saldo de gols acumulado ate a rodada."
        tests:
          - not_null
      - name: position
        description: "Posicao no ranking da rodada."
        tests:
          - not_null

  - name: league_summary
    description: "Resumo por liga e temporada."
    tests:
      - unique_combination_of_columns:
          combination_of_columns:
            - competition_sk
            - season
    columns:
      - name: competition_sk
        description: "Chave substituta da competicao."
        tests:
          - not_null
          - relationships:
              to: ref('dim_competition')
              field: competition_sk
      - name: season
        description: "Temporada da competicao."
        tests:
          - not_null
      - name: total_matches
        description: "Total de partidas contabilizadas."
        tests:
          - not_null
      - name: total_goals
        description: "Total de gols marcados na temporada."
        tests:
          - not_null
      - name: avg_goals_per_match
        description: "Media de gols por partida."
        tests:
          - not_null

  - name: player_match_summary
    description: "Resumo de estatisticas por jogador em cada partida."
    columns:
      - name: fixture_player_stat_id
        tests:
          - not_null
          - unique
      - name: match_id
        tests:
          - not_null
          - relationships:
              to: ref('fact_matches')
              field: match_id
      - name: player_sk
        tests:
          - not_null
          - relationships:
              to: ref('dim_player')
              field: player_sk
      - name: team_sk
        tests:
          - not_null
          - relationships:
              to: ref('dim_team')
              field: team_sk

  - name: player_season_summary
    description: "Resumo por temporada de estatisticas individuais."
    tests:
      - unique_combination_of_columns:
          combination_of_columns:
            - competition_sk
            - season
            - player_id
            - team_id
    columns:
      - name: competition_sk
        tests:
          - not_null
      - name: season
        tests:
          - not_null
      - name: player_id
        tests:
          - not_null
      - name: team_id
        tests:
          - not_null

  - name: player_90_metrics
    description: "Metricas por 90 minutos derivadas do resumo sazonal."
    tests:
      - unique_combination_of_columns:
          combination_of_columns:
            - competition_sk
            - season
            - player_id
            - team_id
    columns:
      - name: player_id
        tests:
          - not_null
      - name: goals_per_90
        description: "Gols por 90 minutos."
      - name: assists_per_90
        description: "Assistencias por 90 minutos."
      - name: xg_per_90
        description: "xG por 90 minutos."

  - name: coach_performance_summary
    description: "Desempenho agregado dos tecnicos por tenure."
    tests:
      - unique_combination_of_columns:
          combination_of_columns:
            - provider
            - coach_tenure_id
    columns:
      - name: coach_tenure_id
        tests:
          - not_null
      - name: coach_id
        tests:
          - not_null
      - name: team_id
        tests:
          - not_null
      - name: matches
        tests:
          - not_null

  - name: head_to_head_summary
    description: "Resumo historico de confrontos diretos por par de times."
    tests:
      - unique_combination_of_columns:
          combination_of_columns:
            - provider
            - league_id
            - pair_team_id
            - pair_opponent_id
    columns:
      - name: league_id
        tests:
          - not_null
      - name: pair_team_id
        tests:
          - not_null
      - name: pair_opponent_id
        tests:
          - not_null
      - name: total_matches
        tests:
          - not_null
